Repository Alfresco/alfresco-process-application-deployment, pull requests merged in 2020-06, with the labels that each got.

#40 [AAE-2605] - upgrade Postgressql and activiti cloud community chart t…
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#42 AAE-2769 unify host and fix generated README
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: PR: partially-approved

#43 AAE-2864 update community version for node affinity support
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#44 cleanup leftovers from service merge
  Makefile
  README.md
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
  values-community-to-enterprise.yaml
  values-registry.tmpl
Labels: PR: unreviewed

#45 AAE-2970 release 7.1.0-M8
  Makefile
  docs/create_application_security_client.md
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#47 AAE-2970- update image tag to 7.1.0-M8
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#49 update tag from readMe
  helm/alfresco-process-application/README.md
Labels: PR: reviewed-approved
