Repository Alfresco/alfresco-process-application-deployment, pull requests merged in 2020-04, with the labels that each got.

#7 [AAE-2137] - create pvc for dmn service
  helm/alfresco-process-application/templates/pvc.yaml
  helm/alfresco-process-application/templates/volume-init-job.yaml
  helm/alfresco-process-application/values.yaml
  values-with-pvc.yaml
Labels: PR: reviewed-approved

#9 AAE-2230 merge Preference and RB
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/values.yaml
Labels: PR: unreviewed

#10 AAE-2137 - remove context path from rb
  values-with-pvc.yaml
Labels: PR: reviewed-approved

#13 [AAE-2137] - remove context path from from, script, dmn
  values-with-pvc.yaml
Labels: PR: unreviewed

#14 [AAE-2137] - remove context path from from, script, dmn - from values.yaml
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#15 [AAE-2137] - revert change for context path and add probePath for form service
  helm/alfresco-process-application/values.yaml
  values-with-pvc.yaml
Labels: PR: reviewed-approved

#12 AAE-2251 update helm chart to RB with Preference and DMN
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/templates/NOTES.txt
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#16 [AAE-2137] - update form-service path
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#11 [AAE-2138] - update readme to add steps for Volume and PVC
  README.md
  values-with-pvc.yaml
Labels: PR: partially-approved

#17 [AAE-2137] - fix form -service path
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#18 AAE-2251 removed dmn from values
  helm/alfresco-process-application/README.md
  values-registry.tmpl
  values-with-pvc.yaml
Labels: PR: reviewed-approved

#19 AAE-2296 removed Form because now it is included in RB
  Makefile
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/templates/NOTES.txt
  helm/alfresco-process-application/values.yaml
  values-registry.tmpl
  values-with-pvc.yaml
Labels: PR: reviewed-approved

#20 AAE-2353 enable volume by default
  README.md
  helm/alfresco-process-application/values.yaml
  values-with-pvc.yaml
Labels: PR: reviewed-approved

#21 Changed http value to false to enable https
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#22 AAE-2324 removed script runtime, now merged in RB
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/templates/NOTES.txt
  helm/alfresco-process-application/values.yaml
  values-registry.tmpl
Labels: PR: reviewed-approved

#24 AAE-2329 add CONTENTSERVICE_ENABLED env variable
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#23 Add Digital Workspace to deployment
  Makefile
  helm/alfresco-process-application/requirements.yaml
  helm/alfresco-process-application/values.yaml
  values-registry.tmpl
Labels: PR: reviewed-approved

#25 ACA-3090 add process specific env var to adw
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#26 AAE-2212 add missing parameters to configure GraphiQL
  helm/alfresco-process-application/values.yaml
Labels: PR: partially-approved

#27 AAE-2398 remove not needed env var for spring actuator
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#28 AAE-2399 volume mount path no need to be dynamic
  helm/alfresco-process-application/templates/volume-init-job.yaml
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#29 AAE-2399 volume mount path static and dmn does not need ingress
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#31 AAE-2425 move content service enabled from extraenv to config
  helm/alfresco-process-application/values.yaml
Labels: PR: unreviewed

#30 new version helm chart
  helm/alfresco-process-application/requirements.yaml
Labels: PR: reviewed-approved

#33 fixed github URL
  docs/create_application_security_client.md
Labels: PR: unreviewed

#34 AAE-2499 no need to add our cluster secret for the customers
  README.md
  helm/alfresco-process-application/values.yaml
Labels: PR: reviewed-approved

#35 upgrade community chart requirements to latest
  helm/alfresco-process-application/requirements.yaml
Labels: PR: unreviewed
