Repository Alfresco/alfresco-process-application-deployment, pull requests merged in 2022-11, with the labels that each got.

#195 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.2
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#196 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.3
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#199 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.6
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#131 AAE-8264: migrate from Travis to GH actions
  .github/dependabot.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/main.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
Labels: PR: unreviewed

#203 AAE-8264: use better commit message for helm publish
  .github/workflows/main.yml
Labels: PR: unreviewed

#206 AAE-10136: use helm package path instead of downloading it again
  .github/workflows/main.yml
Labels: PR: unreviewed

#207 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.7
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#210 AAE-11328: used fixed version for gh action bridgecrewio/checkov-action
  .github/dependabot.yml
  .github/workflows/main.yml
Labels: PR: reviewed-approved

#212 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.9
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#214 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.10
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#215 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.11
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#216 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.12
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#217 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.13
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#218 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.14
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#219 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.15
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#221 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.17
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: reviewed-approved

#222 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.18
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#224 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.19
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#225 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.20
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#227 Update runtime-bundle-service and query-service docker images tag to 7.6.1-alpha.1
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed

#228 Update runtime-bundle-service and query-service docker images tag to 7.6.1-alpha.2
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed

#230 Update runtime-bundle-service and query-service docker images tag to 7.6.1-alpha.3
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed

#231 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.21
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#233 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.22
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#234 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.23
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#235 Update runtime-bundle-service and query-service docker images tag to 7.7.0-alpha.24
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#229 fix(AAE-11372): Create alpha releases for alfresco-process-application-deployment
  .github/workflows/main.yml
  .jx/updatebot.yaml
Labels: PR: partially-approved

#236 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.25
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, develop

#237 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.26
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, develop

#240 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.27
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, develop

#239 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.12
  helm/alfresco-process-application/Chart.yaml
  helm/alfresco-process-application/README.md
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, master

#242 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.15
  helm/alfresco-process-application/Chart.yaml
  helm/alfresco-process-application/README.md
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, master

#243 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.28
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, develop

#244 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.16
  helm/alfresco-process-application/Chart.yaml
  helm/alfresco-process-application/README.md
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, master

#238 fix(AAE-11533): Trigger Github prerelease for Helm charts on release candidate tag
  .github/workflows/rc.yml
Labels: PR: unreviewed

#245 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.29
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, develop

#246 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.30
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, develop

#247 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.31
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved, develop
