Repository Alfresco/alfresco-process-application-deployment, pull requests merged in 2022-07, with the labels that each got.

#97 AAE-9367 enable auto-merge for propagation PRs
  .github/workflows/versions-propagation-auto-merge.yml
Labels: PR: partially-approved

#96 Update docker image tags to version 7.5.0-alpha.3
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed

#98 Update docker image tags to version 7.5.0-alpha.4
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed

#101 AAE-9367 trigger auto-merge workflow on PR labeled only
  .github/workflows/versions-propagation-auto-merge.yml
Labels: PR: unreviewed

#104 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.9
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#105 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.11
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#106 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.12
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#107 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.13
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#108 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.14
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#109 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.15
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#110 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.16
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#111 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.17
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#112 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.18
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#113 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.19
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#114 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.20
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#115 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.21
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#116 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.22
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#117 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.23
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#118 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.24
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#119 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.25
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#121 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.27
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#122 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.28
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#123 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.29
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#124 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.30
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#125 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.31
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#126 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.32
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#127 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.33
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#128 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.34
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#129 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.35
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#130 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.36
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#132 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.37
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved

#133 Update runtime-bundle-service and query-service docker images tag to 7.5.0-alpha.38
  helm/alfresco-process-application/README.md
  helm/alfresco-process-application/values.yaml
Labels: updatebot, PR: unreviewed, PR: reviewed-approved
